In [1]:
# 导入 numpy 包
import numpy as np

In [2]:
# 查看包版本以及可用方法
print(np.__version__)
dir(np)

2.3.2


['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [4]:
# numpy创建数组
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 常见的数组创建方法
print(np.arange(1, 10, 2))
print(np.linspace(1, 50, 10, dtype=int))
print(np.random.randn(3, 3))
print(np.random.randint(1, 10, size=(3, 3)).reshape([9, 1]))
print(np.zeros([3, 3]))
print(np.ones([3, 3]))
print(np.empty([3, 3]))

[1 3 5 7 9]
[ 1  6 11 17 22 28 33 39 44 50]
[[ 0.21040078  0.65496701  0.17927748]
 [ 1.51635461 -1.60134226 -0.56207918]
 [ 0.25787452 -0.60573621  2.11815628]]
[[8]
 [3]
 [7]
 [7]
 [3]
 [2]
 [6]
 [2]
 [6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# numpy常见数据操作
data = np.random.randn(3, 3)

In [ ]:
# 修改数据类型
data.astype('int')

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [35]:
# 查看数据
print(data.shape)
print(data.size)
print(data.ndim)

(3, 3)
9
2


In [41]:
# 数组切片
print(data[:2])
print(data[:2, :2])

[[-1.09974482  0.89504469  0.35315094]
 [-0.62826437  0.24851084  0.54044503]]
[[-1.09974482  0.89504469]
 [-0.62826437  0.24851084]]


In [47]:
# 基本运算
data = np.arange(1, 10).reshape(3, 3)
print(data)
print(data.min())
print(data.max())
print(data.mean())
print(data.sum())
print(data.var())
print(data.std())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
5.0
45
6.666666666666667
2.581988897471611
